"""Application-wide constants."""

from __future__ import annotations

from config.constants.billing import (
    CREDITS_HTTP_TIMEOUT_SECONDS,
    ORGANIZATION_ID_ENV,
    USAGE_SECRET_ENV,
    WEBAPP_URL_ENV,
)
from config.constants.coralogix import (
    CORALOGIX_API_KEY_ENV,
    CORALOGIX_APPLICATION_NAME_ENV,
    CORALOGIX_BASE_URL_ENV,
    CORALOGIX_SUBSYSTEM_NAME_ENV,
)
from config.constants.datadog import (
    DATADOG_API_KEY_ENV,
    DATADOG_APP_KEY_ENV,
    DATADOG_SITE_ENV,
)
from config.constants.gitlab import GITLAB_AUTH_TOKEN_ENV, GITLAB_BASE_URL_ENV
from config.constants.groundcover import (
    GROUNDCOVER_API_KEY_ENV,
    GROUNDCOVER_BACKEND_ID_ENV,
    GROUNDCOVER_MCP_TOKEN_ENV,
    GROUNDCOVER_MCP_URL_ENV,
    GROUNDCOVER_TENANT_UUID_ENV,
    GROUNDCOVER_TIMEZONE_ENV,
)
from config.constants.honeycomb import (
    HONEYCOMB_API_KEY_ENV,
    HONEYCOMB_BASE_URL_ENV,
    HONEYCOMB_DATASET_ENV,
)
from config.constants.investigation import MAX_INVESTIGATION_LOOPS
from config.constants.llm import (
    AZURE_OPENAI_API_KEY_ENV,
    AZURE_OPENAI_API_VERSION_ENV,
    AZURE_OPENAI_BASE_URL_ENV,
)
from config.constants.paths import (
    INTEGRATIONS_STORE_PATH,
    OPENSRE_HOME_DIR,
    OPENSRE_TMP_DIR,
    ensure_opensre_tmp_dir,
    get_store_path,
)
from config.constants.platform import IS_WINDOWS
from config.constants.posthog import (
    DEFAULT_POSTHOG_TIMEOUT_SECONDS,
    DEFAULT_POSTHOG_URL,
    POSTHOG_BASE_URL_ENV,
    POSTHOG_CAPTURE_API_KEY,
    POSTHOG_HOST,
    POSTHOG_PERSONAL_API_KEY_ENV,
    POSTHOG_PROJECT_ID_ENV,
    POSTHOG_TIMEOUT_SECONDS_ENV,
)
from config.constants.sentry import (
    DEFAULT_SENTRY_BASE_URL,
    SENTRY_AUTH_TOKEN_ENV,
    SENTRY_BASE_URL_ENV,
    SENTRY_DSN,
    SENTRY_ERROR_SAMPLE_RATE,
    SENTRY_IN_APP_INCLUDE,
    SENTRY_MAX_BREADCRUMBS,
    SENTRY_ORGANIZATION_SLUG_ENV,
    SENTRY_PROJECT_SLUG_ENV,
    SENTRY_TRACES_SAMPLE_RATE,
)
from config.constants.telegram import (
    TELEGRAM_BOT_TOKEN_ENV,
    TELEGRAM_DEFAULT_CHAT_ID_ENV,
)
from config.constants.vercel import VERCEL_API_TOKEN_ENV, VERCEL_TEAM_ID_ENV

__all__ = [
    "AZURE_OPENAI_API_KEY_ENV",
    "AZURE_OPENAI_API_VERSION_ENV",
    "AZURE_OPENAI_BASE_URL_ENV",
    "CORALOGIX_API_KEY_ENV",
    "CORALOGIX_APPLICATION_NAME_ENV",
    "CORALOGIX_BASE_URL_ENV",
    "CORALOGIX_SUBSYSTEM_NAME_ENV",
    "CREDITS_HTTP_TIMEOUT_SECONDS",
    "DATADOG_API_KEY_ENV",
    "DATADOG_APP_KEY_ENV",
    "DATADOG_SITE_ENV",
    "DEFAULT_POSTHOG_TIMEOUT_SECONDS",
    "DEFAULT_POSTHOG_URL",
    "DEFAULT_SENTRY_BASE_URL",
    "GITLAB_AUTH_TOKEN_ENV",
    "GITLAB_BASE_URL_ENV",
    "GROUNDCOVER_API_KEY_ENV",
    "GROUNDCOVER_BACKEND_ID_ENV",
    "GROUNDCOVER_MCP_TOKEN_ENV",
    "GROUNDCOVER_MCP_URL_ENV",
    "GROUNDCOVER_TENANT_UUID_ENV",
    "GROUNDCOVER_TIMEZONE_ENV",
    "HONEYCOMB_API_KEY_ENV",
    "HONEYCOMB_BASE_URL_ENV",
    "HONEYCOMB_DATASET_ENV",
    "INTEGRATIONS_STORE_PATH",
    "IS_WINDOWS",
    "MAX_INVESTIGATION_LOOPS",
    "OPENSRE_HOME_DIR",
    "OPENSRE_TMP_DIR",
    "ORGANIZATION_ID_ENV",
    "POSTHOG_BASE_URL_ENV",
    "POSTHOG_CAPTURE_API_KEY",
    "POSTHOG_HOST",
    "POSTHOG_PERSONAL_API_KEY_ENV",
    "POSTHOG_PROJECT_ID_ENV",
    "POSTHOG_TIMEOUT_SECONDS_ENV",
    "SENTRY_AUTH_TOKEN_ENV",
    "SENTRY_BASE_URL_ENV",
    "SENTRY_DSN",
    "SENTRY_ERROR_SAMPLE_RATE",
    "SENTRY_IN_APP_INCLUDE",
    "SENTRY_MAX_BREADCRUMBS",
    "SENTRY_ORGANIZATION_SLUG_ENV",
    "SENTRY_PROJECT_SLUG_ENV",
    "SENTRY_TRACES_SAMPLE_RATE",
    "TELEGRAM_BOT_TOKEN_ENV",
    "TELEGRAM_DEFAULT_CHAT_ID_ENV",
    "USAGE_SECRET_ENV",
    "VERCEL_API_TOKEN_ENV",
    "VERCEL_TEAM_ID_ENV",
    "WEBAPP_URL_ENV",
    "ensure_opensre_tmp_dir",
    "get_store_path",
]
