"""GitHub MCP environment variable names."""

from __future__ import annotations

GITHUB_MCP_MODE_ENV = "GITHUB_MCP_MODE"
GITHUB_MCP_URL_ENV = "GITHUB_MCP_URL"
GITHUB_MCP_COMMAND_ENV = "GITHUB_MCP_COMMAND"
GITHUB_MCP_ARGS_ENV = "GITHUB_MCP_ARGS"
GITHUB_MCP_AUTH_TOKEN_ENV = "GITHUB_MCP_AUTH_TOKEN"
GITHUB_MCP_TOOLSETS_ENV = "GITHUB_MCP_TOOLSETS"

__all__ = [
    "GITHUB_MCP_ARGS_ENV",
    "GITHUB_MCP_AUTH_TOKEN_ENV",
    "GITHUB_MCP_COMMAND_ENV",
    "GITHUB_MCP_MODE_ENV",
    "GITHUB_MCP_TOOLSETS_ENV",
    "GITHUB_MCP_URL_ENV",
]
