"""Environment names for long-term memory."""

from __future__ import annotations

OPENSRE_MEMORY_AUTOEXTRACT_DISABLED_ENV = "OPENSRE_MEMORY_AUTOEXTRACT_DISABLED"
OPENSRE_MEMORY_DIR_ENV = "OPENSRE_MEMORY_DIR"
OPENSRE_MEMORY_DISABLED_ENV = "OPENSRE_MEMORY_DISABLED"

__all__ = [
    "OPENSRE_MEMORY_AUTOEXTRACT_DISABLED_ENV",
    "OPENSRE_MEMORY_DIR_ENV",
    "OPENSRE_MEMORY_DISABLED_ENV",
]
