"""Constants for the in-tree OpenSRE AWS infrastructure Terraform contract."""

from __future__ import annotations

OPENSRE_INFRA_AWS_REPO_URL = "https://github.com/Tracer-Cloud/opensre-infra-aws/tree/main"
OPENSRE_INFRA_AWS_GIT_URL = "https://github.com/Tracer-Cloud/opensre-infra-aws.git"
OPENSRE_INFRA_AWS_DIR_ENV = "OPENSRE_INFRA_AWS_DIR"
OPENSRE_INFRA_AWS_ENVIRONMENT_ENV = "OPENSRE_INFRA_AWS_ENVIRONMENT"
# Private opensre-infra-aws git submodule checkout path in this repository.
OPENSRE_INFRA_AWS_SUBMODULE_RELATIVE_PATH = "platform/deployment_multi_tenant"

OPENSRE_INFRA_AWS_SHARED_STACK_RELATIVE_PATH = "stacks/shared"
OPENSRE_INFRA_AWS_MEMORIES_OUTPUT_NAME = "memories"
OPENSRE_INFRA_AWS_DEFAULT_WORKSPACE = "default"

OPENSRE_INFRA_AWS_FILE_SYSTEM_ID_FIELD = "file_system_id"
OPENSRE_INFRA_AWS_FILE_SYSTEM_ARN_FIELD = "file_system_arn"
OPENSRE_INFRA_AWS_CLIENT_SECURITY_GROUP_ID_FIELD = "client_security_group_id"
OPENSRE_INFRA_AWS_BUCKET_NAME_FIELD = "bucket_name"
OPENSRE_INFRA_AWS_BUCKET_ARN_FIELD = "bucket_arn"
OPENSRE_INFRA_AWS_SUBNET_IDS_FIELD = "subnet_ids"

FLEET_CDK_PARAM_S3_FILE_SYSTEM_ID = "S3FileSystemId"
FLEET_CDK_PARAM_S3_FILE_SYSTEM_ARN = "S3FileSystemArn"
FLEET_CDK_PARAM_S3_FILES_CLIENT_SECURITY_GROUP_ID = "S3FilesClientSecurityGroupId"

__all__ = [
    "FLEET_CDK_PARAM_S3_FILE_SYSTEM_ARN",
    "FLEET_CDK_PARAM_S3_FILE_SYSTEM_ID",
    "FLEET_CDK_PARAM_S3_FILES_CLIENT_SECURITY_GROUP_ID",
    "OPENSRE_INFRA_AWS_BUCKET_ARN_FIELD",
    "OPENSRE_INFRA_AWS_BUCKET_NAME_FIELD",
    "OPENSRE_INFRA_AWS_CLIENT_SECURITY_GROUP_ID_FIELD",
    "OPENSRE_INFRA_AWS_DEFAULT_WORKSPACE",
    "OPENSRE_INFRA_AWS_DIR_ENV",
    "OPENSRE_INFRA_AWS_ENVIRONMENT_ENV",
    "OPENSRE_INFRA_AWS_FILE_SYSTEM_ARN_FIELD",
    "OPENSRE_INFRA_AWS_FILE_SYSTEM_ID_FIELD",
    "OPENSRE_INFRA_AWS_GIT_URL",
    "OPENSRE_INFRA_AWS_MEMORIES_OUTPUT_NAME",
    "OPENSRE_INFRA_AWS_REPO_URL",
    "OPENSRE_INFRA_AWS_SHARED_STACK_RELATIVE_PATH",
    "OPENSRE_INFRA_AWS_SUBMODULE_RELATIVE_PATH",
    "OPENSRE_INFRA_AWS_SUBNET_IDS_FIELD",
]
