"""Generated views over the memory directory: MEMORY.md and the prompt index."""

from __future__ import annotations

from pathlib import Path

from core.domain.memory.files import write_text_atomically
from core.domain.memory.models import MemoryRecord

_INDEX_FILENAME = "MEMORY.md"
_INDEX_HEADER = (
    "# Long-term memory index\n"
    "\n"
    "<!-- Generated by OpenSRE after every memory write; safe to delete "
    "(rebuilt on next write). Edit the individual .md files instead. -->\n"
    "\n"
)

DEFAULT_PROMPT_INDEX_CHARS = 4_000
_MAX_PROMPT_ENTRIES = 50


def _index_line(record: MemoryRecord) -> str:
    updated_day = record.updated_at[:10]
    return f"- [{record.memory_type}] {record.slug} — {record.description} (updated {updated_day})"


def write_index(directory: Path, records: list[MemoryRecord]) -> Path:
    """Rewrite MEMORY.md from supplied records. May raise ``OSError``."""
    lines = [_index_line(record) for record in records]
    body = "\n".join(lines) + "\n" if lines else "(no memories stored yet)\n"
    path = directory / _INDEX_FILENAME
    write_text_atomically(path, _INDEX_HEADER + body)
    return path


def render_prompt_index(
    records: list[MemoryRecord],
    *,
    max_chars: int = DEFAULT_PROMPT_INDEX_CHARS,
) -> str:
    """Compact index block for the system prompt; "" when nothing is stored.

    Most recently updated memories come first; when the entry or character
    budget runs out, a tail line points the agent at ``memory_recall``.
    """
    if not records:
        return ""

    lines: list[str] = []
    remaining = max(max_chars, 0)
    shown = 0
    for record in records[:_MAX_PROMPT_ENTRIES]:
        line = _index_line(record)
        if len(line) + 1 > remaining:
            break
        lines.append(line)
        remaining -= len(line) + 1
        shown += 1
    if not lines:
        return ""
    hidden = len(records) - shown
    if hidden > 0:
        lines.append(f"… and {hidden} more memories (use memory_recall)")
    return "\n".join(lines)


__all__ = ["DEFAULT_PROMPT_INDEX_CHARS", "render_prompt_index", "write_index"]
