from typing import Any

def machine() -> str: ...
def node() -> str: ...
def platform(aliased: bool = ..., terse: bool = ...) -> str: ...
def python_version() -> str: ...
def release() -> str: ...
def system() -> str: ...
def __getattr__(name: str) -> Any: ...
