name: Lint PR using PyLint

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: pip install uv

      - name: Install project dependencies
        run: |
          uv sync --frozen --extra dev

      - name: Install pylint
        run: |
          uv pip install pylint

      - name: Analyse code with pylint
        run: |
          uv run pylint $(git ls-files '*.py')